---
- - :permit
  - MIT
  - &1
    :who:
    :why:
    :versions: []
    :when: 2024-09-18 04:48:24.532612000 Z
- - :permit
  - Apache 2.0
  - *1
- - :permit
  - ISC
  - :who:
    :why:
    :versions: []
    :when: 2024-09-18 06:17:35.742242000 Z
- - :permit
  - New BSD
  - &2
    :who:
    :why:
    :versions: []
    :when: 2024-09-18 06:27:28.918434000 Z
- - :permit
  - Simplified BSD
  - *2
- - :permit
  - BSD Zero Clause License
  - :who:
    :why:
    :versions: []
    :when: 2024-09-18 06:33:58.436978000 Z
- - :approve
  - gitconfiglocal
  - :who:
    :why: The BSD license in package.json is wrong. See https://github.com/soldair/node-gitconfiglocal/pull/13
    :versions: []
    :when: 2024-09-18 06:35:16.597322000 Z
- - :permit
  - BlueOak-1.0.0
  - :who:
    :why:
    :versions: []
    :when: 2024-09-18 06:43:07.596790000 Z
- - :permit
  - The Unlicense
  - :who:
    :why:
    :versions: []
    :when: 2024-09-18 06:46:06.140937000 Z
- - :approve
  - "@vercel/flags"
  - :who:
    :why: The license is none. Check https://github.com/route06inc/giselle/issues/12 later
    :versions: []
    :when: 2024-10-08 09:38:17.316315298 Z
- - :permit
  - Zlib
  - :who:
    :why: To not conflict with Apache-2.0 license. https://zlib.net/zlib_license.html
    :versions: []
    :when: 2024-10-11 06:16:13.501764000 Z
