name: CI

on:
  - push
  - pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2.2.1
        with:
          version: 1.9.4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Run Biome
        run: biome ci .
      - name: Test
        run: bun test --coverage
